#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias aigis='ssh dave@aigis'

PS1='[\u@\h \W]\$ '

PATH="$PATH":~/.gem/ruby/1.9.1/bin
export PATH
